# Generated by Django 4.2.9 on 2024-11-10 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0001_initial'),
        ('rss_client', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Source',
        ),
        migrations.AlterField(
            model_name='group',
            name='sources',
            field=models.ManyToManyField(help_text='sources associated with the group', related_name='group', to='sources.source'),
        ),
    ]
