# Generated by Django 4.2.9 on 2024-11-10 12:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss_client', '0002_delete_source_alter_group_sources'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='sources',
        ),
    ]
