# Generated by Django 4.2.9 on 2024-11-11 09:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_client', '0003_remove_group_sources'),
    ]

    operations = [
        migrations.AddField(
            model_name='feed',
            name='external_id',
            field=models.CharField(default=0, help_text='ID from the original news source', max_length=255, unique=True),
            preserve_default=False,
        ),
    ]
