# Generated by Django 4.2.9 on 2024-11-11 10:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_client', '0004_feed_external_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='feed',
            name='external_id',
            field=models.CharField(help_text='ID from the original news source', max_length=5000, unique=True),
        ),
        migrations.AlterField(
            model_name='feed',
            name='url',
            field=models.URLField(help_text='rss url', max_length=5000, unique=True),
        ),
    ]
