# Generated by Django 4.2.9 on 2024-11-11 13:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('sources', '0003_alter_source_group'),
        ('rss_client', '0005_alter_feed_external_id_alter_feed_url'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Group',
        ),
    ]
