# Generated by Django 4.2.9 on 2024-11-12 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss_client', '0006_delete_group'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userquery',
            name='user',
        ),
        migrations.DeleteModel(
            name='ConversationLog',
        ),
        migrations.DeleteModel(
            name='UserQuery',
        ),
    ]
