# Generated by Django 4.2.9 on 2024-11-21 09:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss_client', '0007_remove_userquery_user_delete_conversationlog_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='processedfeed',
            name='feed',
        ),
    ]
