# Generated by Django 4.2.9 on 2024-11-24 15:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('rss_client', '0009_subscriber'),
    ]

    operations = [
        migrations.CreateModel(
            name='TagCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='tag category name', max_length=100, unique=True)),
                ('slug', models.SlugField(help_text='tag category slug', max_length=100, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
        ),
        migrations.AddField(
            model_name='tag',
            name='category',
            field=models.ForeignKey(help_text='tag category', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='tags', to='rss_client.tagcategory'),
        ),
    ]
