# Generated by Django 4.2.9 on 2024-11-25 09:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss_client', '0010_tagcategory_tag_category'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='tag',
            unique_together={('name', 'category')},
        ),
    ]
