# Generated by Django 4.2.9 on 2024-11-25 09:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('rss_client', '0011_alter_tag_unique_together'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='tag',
            name='slug',
        ),
        migrations.RemoveField(
            model_name='tagcategory',
            name='slug',
        ),
    ]
