# Generated by Django 4.2.9 on 2024-11-27 11:03

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rss_client', '0012_remove_tag_slug_remove_tagcategory_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='processedfeed',
            name='user',
            field=models.ForeignKey(help_text='user associated with the processed feed', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='processed_feeds', to=settings.AUTH_USER_MODEL),
        ),
    ]
