# Generated by Django 4.2.9 on 2024-11-27 11:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rss_client', '0013_processedfeed_user'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='subscriber',
            name='email',
        ),
        migrations.RemoveField(
            model_name='subscriber',
            name='name',
        ),
        migrations.AddField(
            model_name='subscriber',
            name='user',
            field=models.ForeignKey(help_text='user associated with the subscriber', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subscribers', to=settings.AUTH_USER_MODEL),
        ),
    ]
