# Generated by Django 4.2.9 on 2024-11-27 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('rss_client', '0014_remove_subscriber_email_remove_subscriber_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='tag',
            name='name',
            field=models.CharField(help_text='tag name', max_length=100),
        ),
    ]
