# Generated by Django 4.2.9 on 2024-11-27 16:30

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('rss_client', '0016_alter_feed_url'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='feed',
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name='feed',
            name='external_id',
            field=models.CharField(help_text='ID from the original news source', max_length=5000),
        ),
        migrations.AlterUniqueTogether(
            name='feed',
            unique_together={('user', 'url', 'external_id')},
        ),
    ]
