# Generated by Django 4.2.9 on 2024-12-12 13:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("sources", "0003_alter_source_group"),
        (
            "rss_client",
            "0017_alter_feed_unique_together_alter_feed_external_id_and_more",
        ),
    ]

    operations = [
        migrations.AddField(
            model_name="feed",
            name="source",
            field=models.ForeignKey(
                help_text="source associated with the feed",
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="feeds",
                to="sources.source",
            ),
        ),
    ]
