# Generated by Django 4.2.9 on 2024-11-12 14:28

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserQuery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(help_text='query question')),
                ('answer', models.TextField(help_text='query answer')),
                ('date_range_start', models.DateField(verbose_name='Date Range Start')),
                ('date_range_end', models.DateField(verbose_name='Date Range End')),
                ('tags', models.JSONField(default=list, help_text='query tags', null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(help_text='user associated with the query', on_delete=django.db.models.deletion.CASCADE, related_name='user_queries', to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='ConversationLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField(help_text='conversation message')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('query', models.ForeignKey(help_text='query associated with the conversation log', on_delete=django.db.models.deletion.CASCADE, related_name='conversation_logs', to='chat.userquery')),
                ('user', models.ForeignKey(help_text='user associated with the conversation log', on_delete=django.db.models.deletion.CASCADE, related_name='conversation_logs', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
