# Generated by Django 4.2.9 on 2024-11-13 08:05

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='conversationlog',
            name='query',
            field=models.ForeignKey(help_text='query associated with the conversation log', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='conversation_logs', to='chat.userquery'),
        ),
        migrations.AlterField(
            model_name='userquery',
            name='date_range_end',
            field=models.DateField(null=True, verbose_name='Date Range End'),
        ),
        migrations.AlterField(
            model_name='userquery',
            name='date_range_start',
            field=models.DateField(null=True, verbose_name='Date Range Start'),
        ),
    ]
