# Generated by Django 4.2.9 on 2024-12-01 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0002_alter_conversationlog_query_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ConversationLog',
        ),
    ]
