# Generated by Django 4.2.9 on 2024-11-12 14:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_alter_user_managers_remove_user_username'),
        ('accounts', '0003_alter_user_username'),
    ]

    operations = [
    ]
