# Generated by Django 4.2.9 on 2024-12-11 14:42

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0005_alter_user_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="uid",
            field=models.UUIDField(
                default=uuid.uuid4, editable=False, help_text="Unique User Identifier"
            ),
        ),
    ]
