# Generated by Django 4.2.9 on 2024-12-11 14:43

from django.db import migrations, models
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ("accounts", "0006_user_uid"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="uid",
            field=models.UUIDField(
                default=uuid.uuid4,
                editable=False,
                help_text="Unique User Identifier",
                unique=True,
            ),
        ),
    ]
