# Generated by Django 4.2.9 on 2024-11-11 13:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0001_initial'),
        ('sources', '0002_rename_rss_url_source_url_source_group_source_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='source',
            name='group',
            field=models.ForeignKey(help_text='group associated with the source', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sources', to='groups.group'),
        ),
    ]
